# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88981af83ab2e3c745bf9997554a77a9e76a1e5e7b0fd96acd4160e730cdf00980b26f0af6e361cff8a6eac9ffb94c7bfacaa772cc1008778494f183b335286

test:
  secret_key_base: 94d9119a756fcfa13b8ab7e7786c5fc5068f5bdd35ef6a80c9ccb66ebbbb4da2ce1d9fb79f569df74912beda447a128685bdb80fd4cdb93e756798e7b5762db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
